music/urls.py
from django.conf.urls import url
from music import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name= 'index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name = 'detail'),
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name = 'favorite'),
    ]

my_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from music import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^music/', include('music.urls', namespace = 'music')),
    #path('music/<int:album_id>/', views.detail, name = 'detail')
    #path('music/<int:album_id>/favorite/' ,views.favorite, name = 'favorite')
]

music/models.py
from django.db import models

class album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title+ '-'+ self.artist

class song(models.Model):
    album = models.ForeignKey(album, on_delete=models.CASCADE)
    file_type= models.CharField(max_length=10)
    song_title = models.CharField(max_length=150)
    is_fav = models.BooleanField(default = False)

    def __str__(self):
        return self.song_title+ '.'+ self.file_type

music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from music.models import album, song

def index(request):
    all_albums = album.objects.all()
    context = {'all_albums': all_albums}
    return render(request,'music/index.html' ,context)

def detail(request, album_id):
       #albums = album.objects.get(pk=album_id)
        albums = get_object_or_404(album, pk=album_id)
        return render(request,'music/detail.html',{'album' : albums})

def favorite(request, album_id):
      albums = get_object_or_404(album, pk= album_id)
      
      try:
          selected_song = albums.song_set.get(pk=request.POST['song'])
      except (KeyError, song.DoesNotExist):
          return render(request, 'music/detail.html', {'album' : albums ,
          'error_message': "You did not select a valid song"})
      else:
          selected_song.is_fav = True
          selected_song.save()
          return render(request, 'music/detail.html', {'album' : albums})

music/templates/music/detail.html
<img src = {{album.album_logo}}>
<h1> {{album.album_title}} </h1>
<h2>{{album.artist}} </h2>

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action= "{% url 'music:favorite' album.id %}" method ="post">
   {% csrf_token %}
   {% for song in album.song_set.all %}
       <input type= "radio" id = "song{{forloop.counter }}" name = "song" value ="{{song.id}}">
       <label for ="song{{forloop.counter}}">
         {{song.song_title}}
         {% if song.is_fav %}
            <img src= "http://i.imgur.com/b9b13Rd.png"/>
         {% endif %}
       </label><br>
   {% endfor %}
   <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
<!-- Loads the path to your static files-->
{% load staticfiles %}
<link rel ="stylesheet" type = "text/css" href= "{% static 'music/style.css' %}"/>

<nav class= "navbar navbar-default">
  <div class = "container-fluid">
    <!-- LOGO-->
      <div class = "navbar-header">
        <a class = "navbar-brand" href ="{% url 'music:index' %}"> Sangeet!! </a>
  </div>
</nav>

{% if all_albums %}
 <h1>HERE ARE ALL THE ALBUMS!!! :)</h1>
 <u1>
  {% for albums in all_albums %}
   <li><a href="{% url 'music:detail' albums.id %}">{{albums.album_title }} => {{albums.artist}} </a></li>

  {% endfor %}
 </u1>
{%else%}
  <h3>"No Albums Available"</h3>
  <h3>"TRY AGAIN!!!"</h3>
{% endif %}